### PR TITLE
pull from master

### PR DESCRIPTION
**Pull request by eugeneloza**
emm... why 16 commits only?! Those were over 100... Something really got messed up with git :) Maybe due to cherry-picking?
I should try merging it command-line.

### CODE REVIEW

**Comment by michaliskambi** [comment]
Hint: You can clone the "upstream" (mine) CGE repository to a separate directory (`git clone https://github.com/castle-engine/castle-engine/ castle-engine-upstream`) and compare the two directories (`diff -ur --exclude=.git castle-engine-upstream/ castle-engine-mine/`). That's what I would do to see if any content is missing or not.

You can also use GitHub to compare:
- https://github.com/castle-engine/castle-engine/compare/
- By clicking you can get to https://github.com/castle-engine/castle-engine/compare/master...eugeneloza:master
- ... which shows that everything is equal, OK. (But this uses GIT magic to compare, so if you don't trust it -- you can follow my hint with `diff -ur ...`)

**Comment by eugeneloza** [comment]
> You can also use GitHub to compare

Thanks, Yes, I've tried this, and I get 16 commits (40 files changed) instead of 100+. I'll try command-line git diff somewhere soon.

**Comment by michaliskambi** [comment]
Note that you can use "normal" diff program on Linux (or Unix, or Cygwin on Windows) too, that's why I suggested `diff -ur --exclude=.git ...`.

It's part of "GNU diffutils", for 90% you have it already installed on your Linux:)

It's not part of GIT, it just compares dir contents. That's what I would use when I wouldn't be sure if GIT / GitHub did the job correctly :)

**Comment by eugeneloza** [comment]
> It's part of "GNU diffutils"

Thanks! I'll try this soon :)

**Comment by eugeneloza** [comment]
Ok, taking a deep breath and merging :) I hope I won't have to delete this fork and recreate it again as the last time :D

**Comment by eugeneloza** [comment]
Yep, looks like the merge was successful! Thanks @michaliskambi !

> diff -ur --exclude=.git castle-engine/ castle-engine-master/
> Only in castle-engine/examples/random_generator: testhash.lps
> Only in castle-engine/packages: castle_base.pas
> Only in castle-engine/packages: castle_components.pas
> Only in castle-engine/packages: castle_window.pas
> Only in castle-engine/src/base: backup
> Only in castle-engine/src/components: backup
> Only in castle-engine/src/game: backup
> Only in castle-engine/src/images: backup
> Only in castle-engine/src/ui: backup
> Only in castle-engine/src/ui/opengl: backup
> Only in castle-engine/src/window: backup
> Only in castle-engine/src/window/gtk: backup
> Only in castle-engine/src/window/unix: backup
> Only in castle-engine/src/window/windows: backup
>

**Pull request merged**
